name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast1
  SERVICE_NAME: fastapi-search-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker

    - name: Create credential file
      run: |
        echo '${{ secrets.GCP_CREDENTIALS }}' > credential_bq.json

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="ARANGO_URL=${{ secrets.ARANGO_URL }}" \
          --set-env-vars="ARANGO_USERNAME=${{ secrets.ARANGO_USERNAME }}" \
          --set-env-vars="ARANGO_PASSWORD=${{ secrets.ARANGO_PASSWORD }}" \
          --set-env-vars="MYSQL_HOST=${{ secrets.MYSQL_HOST }}" \
          --set-env-vars="MYSQL_PORT=${{ secrets.MYSQL_PORT }}" \
          --set-env-vars="MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}" \
          --set-env-vars="MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" \
          --set-env-vars="MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}"
